site_name: Power Simulator Doc
theme: 
    name: material
    language: 'ja'
    icon:
        logo: material/book-open-page-variant
    features:
        - navigation.tabs
    palette:
        scheme: default
        primary: light blue
        accent: light blue

nav:
    - Home: index.md
    - How to Use: how_to_use.md
    - Class Definition:
        - class_definition: Class/class.md
        - PowerNetwork: 
            - power_network: Class/PowerNetwork/power_network.md
            - network_68bus: Class/PowerNetwork/network_68bus.md
        - Bus: 
            - bus: Class/Bus/bus.md
            - bus_non_unit: Class/Bus/bus_non_unit.md
            - bus_PV: Class/Bus/bus_PV.md
            - bus_PQ: Class/Bus/bus_PQ.md
            - bus_slack: Class/Bus/bus_slack.md
        - Component:
            - component: Class/Component/component.md
            - component_empty: Class/Component/component_empty.md
            - Generator AGC:
              - generator_AGC: Class/Component/GeneratorAGC/generator_AGC.md
              - generator: Class/Component/GeneratorAGC/generator.md
            - Load Varying Impedance:
              - load_varying_impedance: Class/Component/LoadVaryingImpedance/load_varying_impedance.md
              - load_const_impedance: Class/Component/LoadVaryingImpedance/load_const_impedance.md
            - Load Varying Power:
              - load_varying_power: Class/Component/LoadVaryingPower/load_varying_power.md
              - load_const_power: Class/Component/LoadVaryingPower/load_const_power.md
        - Controller:
            - controller: Class/Controller/controller.md
            - controller_broadcast_PI: Class/Controller/controller_broadcast_PI.md
            - ControllerRetrofitGenerator:
              - controller_retrofit_generator: Class/Controller/ControllerRetrofitGenerator/controller_retrofit_generator.md
              - ControllerRetrofitGeneratorNonlinear:
                - controller_retrofit_generator_nonlinear: Class/Controller/ControllerRetrofitGenerator/ControllerRetrofitGeneratorNonlinear/controller_retrofit_generator_nonlinear.md
                - controller_retrofit_type1: Class/Controller/ControllerRetrofitGenerator/ControllerRetrofitGeneratorNonlinear/controller_retrofit_type1.md
    - Modeling:
      - modeling: Modeling/modeling.md
    - Power Network:
      - power_network: PowerNetwork/power_network.md
    - System ID:
      - systemID: SystemID/systemID.md
      - Model:
        - model: SystemID/Model/model.md
      - ModelSS:
        - model_ss: SystemID/ModelSS/model_ss.md
    - Tools:
      - tools: Tools/tools.md

extra:
    search:
        language: 'jp'
    font:
        text: "Note Sans JP"
        code: "Consolas"
extra_css:
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: true
    - codehilite:
        linenums: true
        guess_lang: false
        use_pygments: false
        noclasses: true
    - footnotes
    - admonition
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'
copyright: 'Copyright © 2020- Tokyo Tech, Ishizaki Lab.'