site_name: Power Simulator Doc
theme: 
    name: material
    language: 'ja'
    icon:
        logo: material/book-open-page-variant
    features:
        - navigation.tabs
    palette:
        scheme: slate
        primary: light blue
        accent: light blue

nav:
    - Home: index.md
    - How to Use: how_to_use.md
    - Class Definition: 
        - power_network: 
            - power_network: class/power_network/index.md
            - network_68bus: class/power_network/network_68bus.md
        - bus: class/bus.md
        - component: class/component.md
        - controller: class/controller.md

extra:
    search:
        language: 'jp'
    font:
        text: "Note Sans JP"
        code: "Consolas"
extra_css:
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: true
    - codehilite:
        linenums: true
        guess_lang: false
        use_pygments: false
        noclasses: true
    - footnotes
    - admonition
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'
copyright: 'Copyright © 2020- Tokyo Tech, Ishizaki Lab.'